### ISSUE TITLE
PHP 8 Deprecation Warning

### ISSUE THREAD

**Issue by ClausMunch** [sinnbeck/markdom#6]
If run in PHP 8, it will throw an "Function libxml_disable_entity_loader() is deprecated"

**Comment by sinnbeck** [comment]
Sadly I haven't had time to upgrade it to php 8 yet, as all of my projects run 7.4. But feel free to send  in a pr,  if you can't wait.
Hopefully I will look into it in a week or two

**Comment by z4nder** [comment]
The problem is in the https://github.com/wasinger/htmlpagedom package, there is already a PR to fix the problem with php 8
https://github.com/wasinger/htmlpagedom/pull/37.
He didn't pass the ci/cd because he needs adjustments in the test, if I implement this PR manually in this package it will work.
So we need:
- [ ] Make https://github.com/wasinger/htmlpagedom/pull/37  pass (if I had continuous integration, it will speed up)
- [ ] Update the htmlpagedom package in this package. We can only wait for this update to be done.
**Maybe i do it**

**Comment by sinnbeck** [comment]
@gadsdev Thanks for the effort! Sadly I am quite busy currently, so I dont have time to look into it currently. I will happily merge a newer version when its ready :)

**Comment by sinnbeck** [comment]
I have released v2
